name: 部署到 Cloudflare Pages

on:
  push:
    branches:
      - 'main' # 当推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出代码
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 第三步：安装依赖
      - name: 安装依赖
        run: npm install

      # 第四步：构建项目
      - name: 构建项目
        run: npm run docs:build # 构建 VitePress 项目

      - name: Deploy to Cloudflare Pages
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_PAGES_ACCOUNT }}
          command: pages deploy docs/.vitepress/dist --project-name=sakurajp